### ISSUE TITLE
Getting Layout Information

### ISSUE THREAD

**Issue by bryantAXS** [soliantconsulting/SimpleFM#24]
Is there currently a way to get layout information using the -view command with SimpleFM? It looks like the Adapter is setup to use $getFmpxmllayoutUri but I don't see that type of result set parsed anywhere?

**Comment by jeremiahsmall** [comment]
This issue was resolved by #27 last September. See https://github.com/soliantconsulting/SimpleFM/blob/master/library/Soliant/SimpleFM/Adapter.php#L356 

```
/**
 * @return \Soliant\SimpleFM\Adapter
 */
public function useLayoutGrammar()
{
    $this->uri = self::FMPXMLLAYOUT_URI;
    return $this;
}

/**
 * @return \Soliant\SimpleFM\Adapter
 */
public function useResultsetGrammar()
{
    $this->uri = self::FMRESULTSET_URI;
    return $this;
}
```
