### ISSUE TITLE
How to count results?

### ISSUE THREAD

**Issue by garak** [soliantconsulting/SimpleFM#33]
I'm trying to implement a pagination, so I need to know the total count of elements in a layout, without fetching every result (imagine a layout with thousand of records).
I couldn't find a way to get a such count, unless using ``-findall`` and getting "count" (that defeats the above purpose).
It would be possible implement something that calls ``-view`` and fetch ``total-count`` value from ``datasource``?

**Comment by jeremiahsmall** [comment]
Yes, the adapter result always contains metadata about the table it returns results on, including the `count` property, regardless of pagination. In other words, you can execute your query with a max of 1, and count will still tell you what the complete set would have returned.

For example, here's a class that extends the AbstractGateway in SimpleFM with a countOfFindBy method:

```
<?php
namespace Application\Gateway;

use Soliant\SimpleFM\ZF2\Gateway\AbstractGateway;
use Application\Entity\Set;

class SetGateway extends AbstractGateway
{
    /**
     * @param array $search
     * @return int
     */
    public function countOfFindBy(array $search)
    {
        foreach ($search as $field => $value) {
            $search[$field] = str_replace('@', '\@', $value);
        }

        $commandArray = array_merge(
            $search,
            $this->maxSkipToCommandArray(1, 0),
            array('-find' => null)
        );
        $this->simpleFMAdapter
            ->setCommandArray($commandArray)
            ->setLayoutname($this->getEntityLayout());
        $result = $this->handleAdapterResult($this->simpleFMAdapter->execute());

        return (int)$result['count'];
    }
}
```

The underlying command array from the above example ends up looking like this (in case you're not implementing it in a gateway):

```
  ["commandarray":protected] => array(3) {
    ["searchField"] => string(6) "Banana"
    ["-max"] => int(1)
    ["-find"] => NULL
  }
```
