### ISSUE TITLE
Add a slow query logger

### ISSUE THREAD

**Issue by jeremiahsmall** [soliantconsulting/SimpleFM#47]
Per recommendation of @lart2150 and @Stiffel an opt-in slow query logger will be proposed for v3.x

**Comment by jeremiahsmall** [comment]
This would still be a neat feature if someone wants to build it.

**Comment by DASPRiD** [comment]
With our new architecture this is actually easy to accomplish without touching SimpleFM at all. All you have to do is introducing a wrapper around the HTTP client you are using, and let it log any request taking longer than X seconds. This is probably a 5-line class.
