### ISSUE TITLE
Url encoding breaks compound find request (and fix)

### ISSUE THREAD

**Issue by chris-schmitz** [soliantconsulting/SimpleFM#53]
I ran into an issue where I was trying to perform a Compound find
request and kept getting a “Invalid CWP Parameter” exception thrown.

After digging in I found it was being caused by the value of the
`-query` key being url encoded. FileMaker’s XML engine apparently looks
for the exact characters (); and ! when consuming the query string.

Removing the url encoding worked part of the way, but I still got an
error because I had a space within the value. After removing all spaces
the query fired correctly.

I cloned the repo, added a fix and went to create a pull request but I got an error saying I didn't have permission to SimpleFM.

<img width="507" alt="screen shot 2015-08-28 at 7 19 06 pm" src="https://cloud.githubusercontent.com/assets/2437424/9559472/b3a5ccb4-4db9-11e5-9bb4-01e6b8e1ec19.png">

Here’s the query string in question before the change:

http://registrationWebuser:[...]@SK-HQ-WKL08.local:80/fmi/xml/fmresultset.xml?-db=CW_SSCMN_CustomWebPublishingInterface
&-lay=web_Workshops
&-query=%21%28q1%29%3B+%21%28q2%29
&-q1=StatusDetail
&-q1.value=Workshop+was+Canceled
&-q2=StatusDetail
&-q2.value=Workshop+is+Over
&-findquery
&-sortfield.1=DateStart
&-sortorder.1=descend
&-sortfield.2=CalculatedFirstSessionTime
&-sortorder.2=ascend
&-max=5
&-skip=30

And here’s the url after the change:

http://registrationWebuser:[...]@SK-HQ-WKL08.local:80/fmi/xml/fmresultset.xml?
-db=CW_SSCMN_CustomWebPublishingInterface
&-lay=web_Workshops
&-query=!(q1);!(q2)
&-q1=StatusDetail
&-q1.value=Workshop+was+Canceled
&-q2=StatusDetail
&-q2.value=Workshop+is+Over
&-findquery
&-sortfield.1=DateStart
&-sortorder.1=descend
&-sortfield.2=CalculatedFirstSessionTime
&-sortorder.2=ascend
&-max=5
&-skip=30

If you'd like the pull request just let me know what I need to do to submit it. If not I can just let you know how I fixed it and you can apply it if you'd like. 

Thanks!

Chris

**Comment by jeremiahsmall** [comment]
Hi Chris, I just came in to look at something else, and saw this comment sitting here, forlorn. Sorry about not replying last summer. To make a pull request, you'd just need to fork the repo first, and commit on a feature branch in your fork. Then you can PR from your fork to the main here.

**Comment by jeremiahsmall** [comment]
I didn't dig into this again, but I assume it's old news, since it was most likely reported on an older major rev. We're on v5 release currently, which has completely rewritten architecture, and full code coverage.
